import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { createServer as createViteServer } from "vite";
import dotenv from "dotenv";
import { GoogleGenAI } from "@google/genai";
import {
  CANONICAL_RECIPES,
  isCanonicalRecipeTitle,
  findCanonicalRecipe,
  getCanonicalImageForRecipe,
  CanonicalRecipe,
} from "./src/data/canonicalRecipes";
import {
  initAuthStore,
  signUpUser,
  loginUser,
  logoutUser,
  getUserByToken,
  getUserData,
  saveUserData,
} from "./src/server/authStore";

dotenv.config();

// Initialize backend persistent data directories
initAuthStore();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json({ limit: "15mb" }));
app.use(express.urlencoded({ limit: "15mb", extended: true }));

// Initialize Gemini SDK with telemetry header (lazy initialization)
let aiClient: GoogleGenAI | null = null;
function getAIClient(): GoogleGenAI | null {
  if (!aiClient && process.env.GEMINI_API_KEY) {
    try {
      aiClient = new GoogleGenAI({
        apiKey: process.env.GEMINI_API_KEY,
        httpOptions: {
          headers: {
            "User-Agent": "aistudio-build",
          },
        },
      });
    } catch (err) {
      console.error("Failed to initialize GoogleGenAI client:", err);
    }
  }
  return aiClient;
}

// Health check endpoint
app.get("/api/health", (_req, res) => {
  res.json({
    status: "ok",
    app: "Smart Shelf AI Kitchen Manager",
    geminiConfigured: Boolean(process.env.GEMINI_API_KEY),
    time: new Date().toISOString(),
  });
});

// ==========================================
// AUTHENTICATION & USER DATA ENDPOINTS
// ==========================================

// Sign Up Endpoint
app.post("/api/auth/signup", (req, res) => {
  try {
    const { name, email, password, confirmPassword } = req.body;
    if (password !== confirmPassword) {
      return res.status(400).json({ error: "Passwords do not match." });
    }
    const result = signUpUser(name, email, password);
    return res.status(201).json(result);
  } catch (err: any) {
    return res.status(err.status || 500).json({ error: err.message || "Failed to create account." });
  }
});

// Login Endpoint
app.post("/api/auth/login", (req, res) => {
  try {
    const { email, password } = req.body;
    const result = loginUser(email, password);
    return res.json(result);
  } catch (err: any) {
    return res.status(err.status || 401).json({ error: err.message || "Invalid email or password." });
  }
});

// Logout Endpoint
app.post("/api/auth/logout", (req, res) => {
  const authHeader = req.headers.authorization || "";
  const token = authHeader.replace(/^Bearer\s+/i, "").trim();
  logoutUser(token);
  return res.json({ success: true, message: "Logged out successfully." });
});

// Get Current User Profile Endpoint
app.get("/api/auth/me", (req, res) => {
  const authHeader = req.headers.authorization || "";
  const token = authHeader.replace(/^Bearer\s+/i, "").trim();
  const user = getUserByToken(token);
  if (!user) {
    return res.status(401).json({ error: "Session expired or invalid. Please sign in." });
  }
  return res.json({ user });
});

// ==========================================
// STATIC FRONTEND FILE SERVING (RENDER)
// ==========================================

// Serve static build files generated by Vite
app.use(express.static(path.join(__dirname, "dist")));

// Serve index.html for all non-API routes (fallback for single-page app)
app.get("*", (req, res) => {
  res.sendFile(path.join(__dirname, "dist", "index.html"));
});

// Get User Isolated Data Endpoint
app.get("/api/user/data", (req, res) => {
  const authHeader = req.headers.authorization || "";
  const token = authHeader.replace(/^Bearer\s+/i, "").trim();
  const user = getUserByToken(token);
  if (!user) {
    return res.status(401).json({ error: "Unauthorized" });
  }
  const data = getUserData(user.id);
  return res.json(data);
});

// Sync User Isolated Data Endpoint
app.post("/api/user/sync", (req, res) => {
  const authHeader = req.headers.authorization || "";
  const token = authHeader.replace(/^Bearer\s+/i, "").trim();
  const user = getUserByToken(token);
  if (!user) {
    return res.status(401).json({ error: "Unauthorized" });
  }
  const { inventory, wasteRecords, shoppingItems, chefHistory, preferences } = req.body;
  saveUserData(user.id, { inventory, wasteRecords, shoppingItems, chefHistory, preferences });
  return res.json({ success: true });
});

// Load Starter Sample Pantry for Authenticated User
app.post("/api/user/load-sample", (req, res) => {
  const authHeader = req.headers.authorization || "";
  const token = authHeader.replace(/^Bearer\s+/i, "").trim();
  const user = getUserByToken(token);
  if (!user) {
    return res.status(401).json({ error: "Unauthorized" });
  }

  const sampleInventory = [
    {
      id: `inv-${Date.now()}-1`,
      name: "Maggi 2-Minute Masala Noodles",
      category: "Pantry",
      quantity: 3,
      unit: "packs",
      expiryDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      location: "Pantry Shelf",
      confidence: "high",
      addedDate: new Date().toISOString().split("T")[0],
      urgencyStatus: "optimal",
    },
    {
      id: `inv-${Date.now()}-2`,
      name: "Farm Fresh Eggs",
      category: "Dairy & Eggs",
      quantity: 6,
      unit: "pcs",
      expiryDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      location: "Refrigerator Door",
      confidence: "high",
      addedDate: new Date().toISOString().split("T")[0],
      urgencyStatus: "warning",
    },
    {
      id: `inv-${Date.now()}-3`,
      name: "Country Tomatoes",
      category: "Produce",
      quantity: 1,
      unit: "kg",
      expiryDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      location: "Vegetable Crisper",
      confidence: "high",
      addedDate: new Date().toISOString().split("T")[0],
      urgencyStatus: "urgent",
    },
  ];

  saveUserData(user.id, { inventory: sampleInventory });
  return res.json({ success: true, inventory: sampleInventory });
});

// AI Chef Conversational Query & Cooking Guidance ("Hey Chef")
app.post("/api/chef/ask", async (req, res) => {
  const { query, activeRecipe, currentStep, userInventory = [], pantryItems } = req.body;

  const userQuery = (query || "").trim();
  const qLower = userQuery.toLowerCase();

  // Extract inventory names list for truth checking
  const invList: Array<{ name: string; quantity: number; unit: string }> = Array.isArray(userInventory)
    ? userInventory.map((i: any) => ({
        name: String(i.name || ""),
        quantity: Number(i.quantity || 0),
        unit: String(i.unit || "unit"),
      }))
    : [];

  const invNames = invList.map((i) => i.name.toLowerCase());

  // Check specifically for Maggi / instant noodles
  const isMaggiQuery =
    qLower.includes("maggi") ||
    qLower.includes("maggie") ||
    qLower.includes("noodle") ||
    qLower.includes("noodles");

  const hasMaggiInInventory = invList.some(
    (i) =>
      i.name.toLowerCase().includes("maggi") ||
      i.name.toLowerCase().includes("maggie") ||
      i.name.toLowerCase().includes("noodle")
  );

  const isTamilTanglish =
    /enna|sapadalam|samayikalam|panna|mudiyum|iruku|irukku|kitta|venum|epdi|seiya|sapdanum/i.test(qLower);

  // If user explicitly asks about Maggi, answer specifically about Maggi!
  if (isMaggiQuery) {
    const hasEggs = invList.some((i) => i.name.toLowerCase().includes("egg") || i.name.toLowerCase().includes("muttai"));
    const hasOnion = invList.some((i) => i.name.toLowerCase().includes("onion") || i.name.toLowerCase().includes("vengayam"));
    const hasTomato = invList.some((i) => i.name.toLowerCase().includes("tomato") || i.name.toLowerCase().includes("thakkali"));

    const availableAddons: string[] = [];
    if (hasEggs) availableAddons.push("Eggs");
    if (hasOnion) availableAddons.push("Onions");
    if (hasTomato) availableAddons.push("Tomatoes");

    if (hasMaggiInInventory) {
      let reply = "";
      if (isTamilTanglish) {
        reply = `Unga My Food inventory-la Maggi irukku! 2-3 minutes-la Classic Masala Maggi ready pannalam.`;
        if (availableAddons.length > 0) {
          reply += ` Unga kitta ${availableAddons.join(", ")} kooda irukku, adhanala ${availableAddons[0]} Maggi kooda try pannalam!`;
        }
      } else {
        reply = `You have Maggi in your kitchen! You can make Classic Masala Maggi in 2-3 minutes.`;
        if (availableAddons.length > 0) {
          reply += ` Available in inventory: Maggi, ${availableAddons.join(", ")}. You can also prepare ${availableAddons[0]} Maggi!`;
        }
      }
      return res.json({
        response: reply,
        timerMinutes: 3,
        source: "chef-inventory-truth",
        dish: "Maggi",
        maggiAvailable: true,
      });
    } else {
      // Maggi is MISSING
      let reply = "";
      if (isTamilTanglish) {
        reply = `Unga My Food storage-la ippo Maggi illa (Missing: Maggi 1 pack). Classic Maggi panna 1.5 cup thanni kothikka vechu, tastemaker pottu 2-3 mins medium flame-la cook pannunga. Maggi-ya Smart Shopping list-la add pannidava?`;
      } else {
        reply = `Maggi is currently not in your My Food inventory (Missing: Maggi 1 pack). To cook classic Maggi: boil 1.5 cups water, add tastemaker and noodle cake, and simmer for 2 to 3 minutes on medium flame. Would you like to add Maggi to your Smart Shopping list?`;
      }
      return res.json({
        response: reply,
        timerMinutes: 3,
        source: "chef-inventory-truth",
        dish: "Maggi",
        maggiAvailable: false,
        missingIngredients: ["Maggi Noodles 1 pack"],
      });
    }
  }

  const ai = getAIClient();
  if (ai) {
    try {
      const systemInstruction = `You are "Chef Narayanan", an expert South Indian master chef and AI Kitchen Assistant in Smart Shelf.
CRITICAL TRUTH & INVENTORY RULES:
1. The user's actual inventory is: ${JSON.stringify(invList)}.
2. NEVER claim an ingredient is available unless it exists in the user's inventory list above!
3. If the user asks for a specific dish, prioritize and answer specifically about that dish.
4. Keep spoken responses concise, warmly encouraging, precise, and practical (1-3 sentences max).
5. If the user speaks in Tamil or Tanglish, reply warmly in Tanglish.`;

      const promptContext = `Context:
Current Active Recipe: ${activeRecipe || "Kitchen Guidance"}
Current Step: ${currentStep || "Cooking"}
User Question: "${userQuery || "What can I cook?"}"`;

      const response = await ai.models.generateContent({
        model: "gemini-3.8-flash",
        contents: promptContext,
        config: {
          systemInstruction,
          temperature: 0.6,
        },
      });

      const replyText = response.text?.trim();
      if (replyText) {
        const timerMatch = replyText.match(/(\d+)\s*(?:minute|min|m)/i);
        const timerMinutes = timerMatch ? parseInt(timerMatch[1], 10) : 5;
        return res.json({
          response: replyText,
          timerMinutes,
          source: "gemini-ai",
        });
      }
    } catch (error: any) {
      console.warn("Gemini API error in chef ask:", error?.message || error);
    }
  }

  // Fallback culinary responses based strictly on actual items
  let fallbackReply = `Chef advice: Keep flame on medium heat so spice flavors infuse without burning.`;
  let timerMinutes = 5;

  if (qLower.includes("substitute") || qLower.includes("tamarind")) {
    fallbackReply = "Use 1.5 tbsp fresh lemon juice plus 1/4 teaspoon jaggery to replace tamarind paste. Add it after switching off the flame.";
    timerMinutes = 0;
  } else if (qLower.includes("next step") || qLower.includes("advance")) {
    fallbackReply = "Pour the crackling mustard and curry leaves tadka immediately into the pot and close the lid for 30 seconds to lock in the aroma.";
    timerMinutes = 1;
  } else if (qLower.includes("boil") || qLower.includes("tomato") || qLower.includes("rasam")) {
    fallbackReply = "Simmer the country tomatoes on medium flame for 6 to 8 minutes until skins naturally split and soften. I have started a 7-minute timer for you.";
    timerMinutes = 7;
  }

  return res.json({
    response: fallbackReply,
    timerMinutes,
    source: "culinary-engine",
  });
});

// AI Recipe Generation Endpoint — Generates recipes dynamically from user ingredients
// AI Recipe Generation Endpoint
// Gemini dynamically creates recipes from the user's ingredients.
// Maggi is the only protected canonical-recipe exception.
app.post("/api/recipes/generate", async (req, res) => {
  const {
    ingredients = [],
    userInventory = [],
    cuisinePreference = "Any",
    dietaryPreference = "Flexible",
    searchQuery = "",
  } = req.body;

  const tamilToEnglishMap: Record<string, string> = {
    maggi: "maggi",
    maggie: "maggi",
    maggy: "maggi",
    maggis: "maggi",
    noodles: "maggi",
    "instant noodles": "maggi",
    thakkali: "tomato",
    thakkalipazham: "tomato",
    vengayam: "onion",
    vengaayam: "onion",
    vengaiyam: "onion",
    muttai: "egg",
    mutta: "egg",
    anda: "egg",
    koli: "chicken",
    kozhi: "chicken",
    chickan: "chicken",
    murgh: "chicken",
    arisi: "rice",
    saatham: "rice",
    sadham: "rice",
    saadham: "rice",
    chawal: "rice",
    urulaikizhangu: "potato",
    urulaikilangu: "potato",
    urulai: "potato",
    aloo: "potato",
    paruppu: "toor dal",
    dhal: "toor dal",
    dal: "toor dal",
    paal: "milk",
    maanga: "mango",
    maangai: "mango",
    mampazham: "mango",
    manga: "mango",
    puli: "tamarind",
    thengai: "coconut",
    thayir: "curd",
    dahi: "curd",
    keerai: "spinach",
    poondu: "garlic",
    lahsun: "garlic",
    inji: "ginger",
    kadugu: "mustard seeds",
    seeragam: "cumin seeds",
    milagu: "black pepper",
    vegetable: "vegetables",
    vegetables: "vegetables",
    veggie: "vegetables",
    veggies: "vegetables",
    kaygari: "vegetables",
    cheese: "cheese",
    paneer: "paneer",
  };

  const normalizeToken = (value: string): string => {
    const cleaned = value.toLowerCase().trim();
    return tamilToEnglishMap[cleaned] || cleaned;
  };

  const rawIngredients = Array.isArray(ingredients)
    ? ingredients
    : [];

  const normalizedIngredients = rawIngredients
    .map((item: any) =>
      normalizeToken(
        typeof item === "string"
          ? item
          : String(item?.name || "")
      )
    )
    .filter(Boolean);

  const normalizedInventory = Array.isArray(userInventory)
    ? userInventory
        .map((item: any) =>
          normalizeToken(
            typeof item === "string"
              ? item
              : String(item?.name || "")
          )
        )
        .filter(Boolean)
    : [];

  const query = String(searchQuery || "").trim();

  const combinedIngredients = Array.from(
    new Set([
      ...normalizedIngredients,
      ...normalizedInventory,
    ])
  );

  /*
   * ------------------------------------------------------------
   * MAGGI PROTECTION
   * ------------------------------------------------------------
   *
   * If the user explicitly asks for Maggi/noodles, do NOT allow
   * Gemini to invent recipe names.
   *
   * Only these five canonical recipes are allowed:
   * Masala Maggi
   * Vegetable Maggi
   * Egg Maggi
   * Cheese Maggi
   * Spicy Garlic Maggi
   */
  const asksForMaggi =
    combinedIngredients.includes("maggi") ||
    /maggi|maggie|maggy|noodle|instant noodles/i.test(query);

  if (asksForMaggi) {
    const allowedMaggiTitles = [
      "Masala Maggi",
      "Vegetable Maggi",
      "Egg Maggi",
      "Cheese Maggi",
      "Spicy Garlic Maggi",
    ];

    const maggiRecipes = CANONICAL_RECIPES.filter((recipe) =>
      allowedMaggiTitles.includes(recipe.title)
    );

    const rankedMaggi = [...maggiRecipes].sort((a, b) => {
      const aRequired = (a.normalizedRequired || []).map((x) =>
        normalizeToken(x)
      );
      const bRequired = (b.normalizedRequired || []).map((x) =>
        normalizeToken(x)
      );

      const aScore = aRequired.filter((x) =>
        combinedIngredients.includes(x)
      ).length;

      const bScore = bRequired.filter((x) =>
        combinedIngredients.includes(x)
      ).length;

      return bScore - aScore;
    });

    const selectedMaggi = rankedMaggi.slice(0, 5);

    const formattedMaggi = selectedMaggi.map((recipe, index) => {
      const ingredientsWithQuantities =
        recipe.ingredientsWithQuantities || [];

      const formattedIngredients =
        ingredientsWithQuantities.map((item) => {
          const token = normalizeToken(item.name);
          const isAvailable =
            combinedIngredients.includes(token);

          return {
            ...item,
            isAvailable,
          };
        });

      const required =
        (recipe.normalizedRequired || []).map((x) =>
          normalizeToken(x)
        );

      const availableRequired = required.filter((x) =>
        combinedIngredients.includes(x)
      ).length;

      const matchPercentage =
        required.length > 0
          ? Math.round(
              (availableRequired / required.length) * 100
            )
          : 100;

      const missingIngredients = formattedIngredients
        .filter((item) => !item.isAvailable)
        .map(
          (item) =>
            `${item.name} (${item.quantity})`
        );

      return {
        id: `maggi-ai-${recipe.id}-${index}`,
        title: recipe.title,
        subtitle: recipe.subtitle,
        prepTime: recipe.prepTime,
        cookTime: recipe.cookTime,
        estimatedCookingTime:
          recipe.estimatedCookingTime,
        servings: recipe.servings,
        description: recipe.description,
        cuisine: recipe.cuisine,
        category: recipe.category,
        image: recipe.image,
        atRiskIngredients: [],
        pantryItems: formattedIngredients
          .filter((item) => item.isAvailable)
          .map((item) => item.name),
        missingIngredients,
        rescueWeight: recipe.rescueWeight,
        moneySaved: recipe.moneySaved,
        wasteSavingTip: recipe.wasteSavingTip,
        steps: recipe.steps,
        ingredientsWithQuantities:
          formattedIngredients,
        substitutions: recipe.substitutions || [],
        matchPercentage,
        isAIGenerated: true,
      };
    });

    return res.json({
      recipes: formattedMaggi,
      source: "maggi-canonical-ai",
      message:
        "Showing only verified Smart Shelf Maggi recipes.",
    });
  }

  /*
   * ------------------------------------------------------------
   * NORMAL AI RECIPE GENERATION
   * ------------------------------------------------------------
   *
   * For every non-Maggi request, Gemini is allowed to create
   * an appropriate recipe even when it does NOT exist in the
   * stored recipe database.
   */

  const ai = getAIClient();

  if (!ai) {
    return res.status(503).json({
      recipes: [],
      source: "ai-unavailable",
      message:
        "Gemini AI is not configured. Please configure GEMINI_API_KEY.",
    });
  }

  const availableItems =
    normalizedInventory.length > 0
      ? normalizedInventory
      : normalizedIngredients;

  const aiPrompt = `
You are the Smart Shelf AI Chef.

The user wants a recipe based on their kitchen ingredients.

USER QUERY:
"${query}"

USER AVAILABLE INGREDIENTS:
${JSON.stringify(availableItems)}

USER REQUESTED INGREDIENTS:
${JSON.stringify(normalizedIngredients)}

CUISINE PREFERENCE:
${cuisinePreference}

DIETARY PREFERENCE:
${dietaryPreference}

IMPORTANT RULES:

1. Generate a REALISTIC recipe that actually matches the user's request.
2. You are NOT restricted to a stored recipe database.
3. You MAY create a recipe that does not exist in Smart Shelf's stored catalog.
4. Prioritize Indian and South Indian homestyle cooking when appropriate.
5. If the user has chicken + rice, Chicken Biryani is an appropriate possible result.
6. Do NOT invent bizarre combinations simply to use every ingredient.
7. Use the user's available ingredients as the primary ingredients.
8. Common pantry basics such as salt, oil, water and basic spices may be assumed when reasonable.
9. If an important ingredient is missing, put it in missingIngredients.
10. NEVER claim a missing ingredient is available.
11. availableIngredientsList must contain only ingredients actually available.
12. missingIngredientsList must contain only ingredients that are not available.
13. Give realistic quantities.
14. Give clear cooking steps.
15. Return ONE best recipe first and optionally up to two alternatives.
16. Do not return Maggi recipes from this general AI path.
17. Do not use fake cuisine labels.
18. The recipe title should be a normal, recognizable dish name.

Return ONLY valid JSON in this format:

{
  "recipes": [
    {
      "title": "Recipe name",
      "subtitle": "Short description",
      "description": "Brief description",
      "cuisine": "Cuisine",
      "category": "Breakfast | Lunch | Dinner | Snack | Side",
      "prepTime": "10 min",
      "cookTime": "20 min",
      "estimatedCookingTime": "30 min",
      "servings": 2,
      "ingredientsWithQuantities": [
        {
          "name": "Chicken",
          "quantity": "250 g",
          "isAvailable": true
        }
      ],
      "availableIngredientsList": ["Chicken", "Rice"],
      "missingIngredientsList": ["Onion"],
      "steps": [
        {
          "stepNumber": 1,
          "title": "Prepare",
          "duration": "5 min",
          "instructions": [
            "Step instruction"
          ]
        }
      ],
      "substitutions": [],
      "wasteSavingTip": "Useful tip"
    }
  ]
}
`;

  const systemInstruction = `
You are a reliable recipe-generation engine.

Your highest priorities are:
- truthful ingredient availability
- realistic recipes
- correct cuisine names
- useful quantities
- simple cooking instructions
- no hallucinated ingredient availability

Never say an ingredient is available unless it appears in the user's
available ingredient list.

Never create fake or nonsensical recipe names.

The user is allowed to receive recipes that are not present in any
stored recipe database.
`;

  try {
   const generateWithRetry = async (attempts = 3): Promise<any> => {
  let lastError: unknown = null;

  for (let attempt = 1; attempt <= attempts; attempt++) {
    try {
      const timeoutPromise = new Promise<never>((_, reject) =>
        setTimeout(
          () =>
            reject(
              new Error(
                "Gemini API call timed out after 20 seconds"
              )
            ),
          20000
        )
      );

      return await Promise.race([
        ai.models.generateContent({
          model: "gemini-3.8-flash",
          contents: aiPrompt,
          config: {
            responseMimeType: "application/json",
            systemInstruction,
          },
        }),
        timeoutPromise,
      ]);
    } catch (error: any) {
      lastError = error;

      const errorText = String(
        error?.message || error || ""
      );

      const isTemporaryError =
        errorText.includes("503") ||
        errorText.includes("UNAVAILABLE") ||
        errorText.includes("high demand") ||
        errorText.includes("temporarily");

      if (!isTemporaryError || attempt === attempts) {
        throw error;
      }

      console.warn(
        `Gemini temporarily unavailable. Retrying (${attempt + 1}/${attempts})...`
      );

      await new Promise((resolve) =>
        setTimeout(resolve, attempt * 2000)
      );
    }
  }

  throw lastError;
};

const response: any = await generateWithRetry(3);

    let jsonText =
      response.text?.trim() || "";

    if (jsonText.startsWith("```")) {
      jsonText = jsonText
        .replace(/^```(?:json)?\s*/i, "")
        .replace(/\s*```$/i, "");
    }

    const parsed = JSON.parse(jsonText);

    const rawRecipes = Array.isArray(parsed)
      ? parsed
      : Array.isArray(parsed?.recipes)
        ? parsed.recipes
        : [parsed];

    const recipes = rawRecipes
      .filter(Boolean)
      .slice(0, 3)
      .map((recipe: any, index: number) => {
        const ingredientsWithQuantities =
          Array.isArray(recipe.ingredientsWithQuantities)
            ? recipe.ingredientsWithQuantities
            : [];

        const formattedIngredients =
          ingredientsWithQuantities.map(
            (item: any) => {
              const name = String(
                item.name || ""
              ).trim();

              const token =
                normalizeToken(name);

              const isAvailable =
                availableItems.includes(token);

              return {
                name,
                quantity: String(
                  item.quantity || "as required"
                ),
                isAvailable,
              };
            }
          );

        const availableIngredientsList =
          formattedIngredients
            .filter((item: any) =>
              item.isAvailable
            )
            .map((item: any) => item.name);

        const missingIngredientsList =
          formattedIngredients
            .filter(
              (item: any) =>
                !item.isAvailable
            )
            .map((item: any) => item.name);

        const totalIngredients =
          formattedIngredients.length;

        const availableCount =
          availableIngredientsList.length;

        const matchPercentage =
          totalIngredients > 0
            ? Math.round(
                (availableCount /
                  totalIngredients) *
                  100
              )
            : 100;

        return {
          id: `ai-generated-${Date.now()}-${index}`,
          title:
            String(
              recipe.title ||
                recipe.recipeName ||
                "AI Kitchen Recipe"
            ),
          subtitle:
            String(
              recipe.subtitle ||
                "Created by Smart Shelf AI"
            ),
          prepTime:
            String(
              recipe.prepTime || "5 min"
            ),
          cookTime:
            String(
              recipe.cookTime || "15 min"
            ),
          estimatedCookingTime:
            String(
              recipe.estimatedCookingTime ||
                ""
            ),
          servings:
            typeof recipe.servings ===
            "number"
              ? recipe.servings
              : 2,
          description:
            String(
              recipe.description ||
                "A recipe created from your available ingredients."
            ),
          cuisine:
            String(
              recipe.cuisine ||
                "Indian"
            ),
          category:
            ["Breakfast", "Lunch", "Dinner", "Snack", "Side"]
              .includes(recipe.category)
              ? recipe.category
              : "Dinner",
          image:
            getCanonicalImageForRecipe(
              String(
                recipe.title ||
                  recipe.recipeName ||
                  "AI Recipe"
              )
            ),
          atRiskIngredients: [],
          pantryItems:
            availableIngredientsList,
          missingIngredients:
            missingIngredientsList,
          rescueWeight: "0",
          moneySaved: "₹0",
          wasteSavingTip:
            recipe.wasteSavingTip ||
            "Use ingredients that are closest to expiry first.",
          steps:
            Array.isArray(recipe.steps)
              ? recipe.steps
              : [],
          ingredientsWithQuantities:
            formattedIngredients,
          substitutions:
            Array.isArray(recipe.substitutions)
              ? recipe.substitutions
              : [],
          availableIngredientsList,
          missingIngredientsList,
          matchPercentage,
          isAIGenerated: true,
        };
      });

    if (recipes.length > 0) {
      return res.json({
        recipes,
        source: "gemini-ai",
        message:
          `Gemini generated ${recipes.length} recipe${recipes.length === 1 ? "" : "s"}.`,
      });
    }

    return res.status(502).json({
      recipes: [],
      source: "gemini-ai",
      message:
        "Gemini did not return a usable recipe.",
    });
  } catch (error: any) {
    console.error(
      "Gemini dynamic recipe generation failed:",
      error?.message || error
    );

    // Gemini can temporarily return 503 when the model is busy.
    // Keep Generate with AI usable with the verified Smart Shelf recipes.
    try {
      const fallbackCandidates = CANONICAL_RECIPES.filter((recipe) => {
        const required = Array.isArray(recipe.normalizedRequired)
          ? recipe.normalizedRequired
          : [];

        return required.some((ingredient: string) =>
          availableItems.includes(normalizeToken(ingredient))
        );
      });

      const rankedFallback = fallbackCandidates
        .map((recipe) => {
          const required = Array.isArray(recipe.normalizedRequired)
            ? recipe.normalizedRequired
            : [];

          const matched = required.filter((ingredient: string) =>
            availableItems.includes(normalizeToken(ingredient))
          );

          const matchPercentage =
            required.length > 0
              ? Math.round((matched.length / required.length) * 100)
              : 0;

          return {
            recipe,
            matchPercentage,
          };
        })
        .filter((item) => item.matchPercentage > 0)
        .sort(
          (a, b) => b.matchPercentage - a.matchPercentage
        )
        .slice(0, 5);

      const fallbackRecipes = rankedFallback.map(
        ({ recipe, matchPercentage }) => ({
          ...recipe,
          image: getCanonicalImageForRecipe(recipe.title),
          availableIngredientsList:
            recipe.normalizedRequired?.filter((ingredient: string) =>
              availableItems.includes(normalizeToken(ingredient))
            ) || [],
          missingIngredientsList:
            recipe.normalizedRequired?.filter((ingredient: string) =>
              !availableItems.includes(normalizeToken(ingredient))
            ) || [],
          matchPercentage,
          isAIGenerated: false,
        })
      );

      if (fallbackRecipes.length > 0) {
        return res.json({
          recipes: fallbackRecipes,
          source: "smart-shelf-fallback",
          message:
            "Gemini is temporarily unavailable. Showing verified Smart Shelf recipes.",
        });
      }
    } catch (fallbackError: any) {
      console.error(
        "Smart Shelf fallback failed:",
        fallbackError?.message || fallbackError
      );
    }

    return res.status(502).json({
      recipes: [],
      source: "gemini-error",
      message:
        "Gemini is temporarily unavailable and no verified fallback recipe was found.",
    });
  }
});

app.post("/api/recipes/recommend", async (req, res) => {
  const { availableItems, preferredCuisine } = req.body;

  const ai = getAIClient();
  if (ai) {
    try {
      const prompt = `Based on these available kitchen inventory items: ${JSON.stringify(availableItems || ["Tomatoes", "Coriander", "Toor Dal", "Carrots", "Coconut", "Mustard Seeds", "Curry Leaves"])}, recommend 3 authentic ${preferredCuisine || "South Indian"} zero-waste recipes prioritizing items closest to expiration. Return JSON.`;

      const response = await ai.models.generateContent({
        model: "gemini-3.8-flash",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          systemInstruction: `You are an AI kitchen manager specialized in South Indian zero-waste cooking.
Provide an array of recipes with title, prepTime, description, rescuedIngredients (list with urgency), pantryItems, missingIngredients (if any), and difficulty.`,
        },
      });

      const parsed = JSON.parse(response.text || "[]");
      if (Array.isArray(parsed) && parsed.length > 0) {
        return res.json({ recipes: parsed, source: "gemini-ai" });
      }
    } catch (error: any) {
      console.warn("Gemini recipe recommendation error, falling back:", error?.message || error);
    }
  }

  // Pre-configured rich South Indian authentic recipes matching the exact designs
  return res.json({
    recipes: [
      {
        id: "tomato-rasam",
        title: "Tomato Rasam",
        subtitle: "Tangy Tomato Rasam (Lemon Infused)",
        prepTime: "25 min",
        servings: 4,
        description: "A comforting, tangy South Indian soup perfect for clearing out overripe tomatoes.",
        atRiskIngredients: [
          { name: "Tomatoes", urgency: "2 days", status: "critical" },
          { name: "Cilantro", urgency: "1 day", status: "urgent" },
        ],
        pantryItems: ["Mustard Seeds", "Curry Leaves", "Hing", "Pepper & Cumin"],
        missingIngredients: [],
        rescueWeight: "560g",
        moneySaved: "₹185",
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=80",
      },
      {
        id: "veg-poriyal",
        title: "Vegetable Poriyal",
        prepTime: "20 min",
        servings: 3,
        description: "A quick stir-fry of mixed vegetables finished with fresh coconut.",
        pantryItems: ["Carrots", "Green Beans", "Coconut", "Urad Dal"],
        atRiskIngredients: [
          { name: "Carrots", urgency: "3 days", status: "warning" },
          { name: "Fresh Grated Coconut", urgency: "16h left", status: "urgent" },
        ],
        missingIngredients: [],
        rescueWeight: "400g",
        moneySaved: "₹95",
        image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&auto=format&fit=crop&q=80",
      },
      {
        id: "veg-sambar",
        title: "Mixed Vegetable Sambar",
        prepTime: "30 min",
        servings: 5,
        description: "A staple South Indian lentil stew packed with drumsticks, carrots, and shallots.",
        pantryItems: ["Toor Dal", "Tamarind", "Drumstick", "Sambar Powder"],
        atRiskIngredients: [
          { name: "Sambar Onions (Shallots)", urgency: "2 days", status: "warning" },
        ],
        missingIngredients: ["Drumstick"],
        rescueWeight: "650g",
        moneySaved: "₹140",
        image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=80",
      },
    ],
    source: "smart-shelf-catalog",
  });
});

// Vite middleware & Static serving
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Smart Shelf Server running at http://0.0.0.0:${PORT}`);
  });
}

startServer();
